# Generated by Django 4.2.7 on 2025-10-02 20:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(upload_to='prescriptions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['.pdf', '.jpg', '.jpeg', '.png'])], verbose_name='Prescription File')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verified At')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('verified_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['pharmacist', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_prescriptions', to=settings.AUTH_USER_MODEL, verbose_name='Verified By')),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
                'db_table': 'prescriptions',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='prescriptio_user_id_6b2e63_idx'), models.Index(fields=['verified_by'], name='prescriptio_verifie_f92d75_idx'), models.Index(fields=['uploaded_at'], name='prescriptio_uploade_e14ce8_idx')],
            },
        ),
    ]
