# Generated by Django 4.2.7 on 2025-10-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='dispensed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dispensed At'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='fill_status',
            field=models.CharField(choices=[('pending_fill', 'Pending Fill'), ('filled', 'Filled'), ('partially_filled', 'Partially Filled'), ('expired', 'Expired')], default='pending_fill', max_length=20, verbose_name='Fill Status'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='refill_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Refill Count'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('filled', 'Filled'), ('refilled', 'Refilled')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['user', 'fill_status'], name='prescriptio_user_id_ad47d4_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['dispensed_at'], name='prescriptio_dispens_1a4d61_idx'),
        ),
    ]
