# Generated by Django 4.2.7 on 2025-10-30 13:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prescriptions', '0002_prescription_dispensed_at_prescription_fill_status_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='prescription',
            name='prescriptio_user_id_ad47d4_idx',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='fill_status',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='refill_count',
        ),
        migrations.AddField(
            model_name='prescription',
            name='added_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['pharmacist', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_prescriptions', to=settings.AUTH_USER_MODEL, verbose_name='Added By'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='dispensed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['pharmacist', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensed_prescriptions', to=settings.AUTH_USER_MODEL, verbose_name='Dispensed By'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient_age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Patient Age'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient_contact',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Patient Contact'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient_gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True, verbose_name='Patient Gender'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient_id_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Patient ID Number'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Patient Name'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='prescribed_medicines',
            field=models.JSONField(default=list, help_text='List of medicines with dosage, quantity, and instructions', verbose_name='Prescribed Medicines'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='prescription_type',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('manual', 'Manual Entry')], default='uploaded', max_length=20, verbose_name='Prescription Type'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='prescriptions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['.pdf', '.jpg', '.jpeg', '.png'])], verbose_name='Prescription File'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('validated', 'Validated'), ('rejected', 'Rejected'), ('dispensed', 'Dispensed'), ('completed', 'Completed')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['status'], name='prescriptio_status_1d7db8_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['added_by'], name='prescriptio_added_b_05295c_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['patient_name'], name='prescriptio_patient_15b304_idx'),
        ),
    ]
