# Generated by Django 4.2.7 on 2026-05-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0003_remove_prescription_prescriptio_user_id_ad47d4_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='fill_status',
            field=models.CharField(choices=[('pending_fill', 'Pending Fill'), ('filled', 'Filled'), ('partially_filled', 'Partially Filled'), ('expired', 'Expired')], default='pending_fill', max_length=20, verbose_name='Fill Status'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='refill_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Refill Count'),
        ),
    ]
