# # Generated by Django 4.2.7 on 2025-10-03 14:25
# 
# from django.conf import settings
# from django.db import migrations, models
# import django.db.models.deletion
# import django.utils.timezone
# 
# 
# class Migration(migrations.Migration):
# 
#     initial = True
# 
#     dependencies = [
#         migrations.swappable_dependency(settings.AUTH_USER_MODEL),
#     ]
# 
#     operations = [
#         migrations.CreateModel(
#             name='Patient',
#             fields=[
#                 ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                 ('first_name', models.CharField(max_length=50)),
#                 ('last_name', models.CharField(max_length=50)),
#                 ('date_of_birth', models.DateField()),
#                 ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('PREFER_NOT_TO_SAY', 'Prefer not to say')], max_length=20)),
#                 ('national_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
#                 ('phone_number', models.CharField(max_length=15)),
#                 ('email', models.EmailField(blank=True, max_length=254, null=True)),
#                 ('address', models.TextField(blank=True)),
#                 ('county', models.CharField(blank=True, max_length=50)),
#                 ('allergies', models.TextField(blank=True, help_text='List of allergies separated by commas (e.g., Penicillin, Nuts)')),
#                 ('medical_history', models.TextField(blank=True, help_text='Summary of relevant medical history')),
#                 ('emergency_contact_name', models.CharField(blank=True, max_length=100)),
#                 ('emergency_contact_phone', models.CharField(blank=True, max_length=15)),
#                 ('is_active', models.BooleanField(default=True)),
#                 ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
#                 ('updated_at', models.DateTimeField(auto_now=True)),
#                 ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL)),
#             ],
#             options={
#                 'verbose_name': 'Patient',
#                 'verbose_name_plural': 'Patients',
#                 'ordering': ['last_name', 'first_name'],
#             },
#         ),
#     ]
