# Generated by Django 4.2.7 on 2025-10-03 14:25

from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('prescription_volume', 'Prescription Volume'), ('inventory_usage', 'Inventory Usage'), ('turnaround_times', 'Turnaround Times'), ('patient_trends', 'Patient Service Trends'), ('compliance_summary', 'Compliance Summary')], max_length=50, verbose_name='Report Type')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('data', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Report Data')),
                ('total_count', models.PositiveIntegerField(default=0, verbose_name='Total Items')),
                ('summary', models.TextField(blank=True, verbose_name='Summary')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Generated At')),
                ('is_exported', models.BooleanField(default=False, verbose_name='Exported')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to=settings.AUTH_USER_MODEL, verbose_name='Generated By')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['type', 'generated_at'], name='reports_rep_type_a6fd55_idx'), models.Index(fields=['start_date', 'end_date'], name='reports_rep_start_d_29aaa5_idx')],
            },
        ),
    ]
