module.exports = {
  darkMode: 'class',
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: 'var(--color-primary)',
          50: 'var(--bg-field)',
          100: 'var(--bg-card)',
          200: 'var(--border-primary)',
          300: 'var(--border-primary)',
          400: 'var(--color-highlight)',
          500: 'var(--color-primary)',
          600: 'var(--color-primary)',
          700: 'var(--text-secondary)',
          800: 'var(--text-primary)',
          900: 'var(--text-primary)',
          950: 'var(--text-primary)',
        },
        secondary: {
          DEFAULT: 'var(--color-highlight)',
          50: 'var(--bg-field)',
          100: 'var(--bg-card)',
          200: 'var(--border-primary)',
          300: 'var(--border-primary)',
          400: 'var(--color-highlight)',
          500: 'var(--color-highlight)',
          600: 'var(--color-accent)',
          700: 'var(--text-secondary)',
          800: 'var(--text-primary)',
          900: 'var(--text-primary)',
          950: 'var(--text-primary)',
        },
        accent: {
          DEFAULT: 'var(--color-accent)',
          50: 'var(--bg-field)',
          100: 'var(--bg-card)',
          200: 'var(--border-primary)',
          300: 'var(--border-primary)',
          400: 'var(--color-highlight)',
          500: 'var(--color-accent)',
          600: 'var(--color-accent)',
          700: 'var(--text-secondary)',
          800: 'var(--text-primary)',
          900: 'var(--text-primary)',
          950: 'var(--text-primary)',
        },
        surface: {
          light: 'var(--color-bg-card-light)',
          dark: 'var(--color-bg-card-dark)',
          "glass-light": "var(--color-bg-card-light)",
          "glass-dark": "var(--color-bg-card-dark)",
        },
        blue: {
          50: 'var(--bg-field)',
          100: 'var(--bg-card)',
          200: 'var(--border-primary)',
          300: 'var(--border-primary)',
          400: 'var(--color-highlight)',
          500: 'var(--color-primary)',
          600: 'var(--color-primary)',
          700: 'var(--text-secondary)',
          800: 'var(--text-primary)',
          900: 'var(--bg-dark)',
          950: 'var(--bg-dark)',
        },
        indigo: {
          50: 'var(--bg-field)',
          100: 'var(--bg-card)',
          200: 'var(--border-primary)',
          300: 'var(--border-primary)',
          400: 'var(--color-highlight)',
          500: 'var(--color-primary)',
          600: 'var(--color-primary)',
          700: 'var(--text-secondary)',
          800: 'var(--text-primary)',
          900: 'var(--bg-dark)',
          950: 'var(--bg-dark)',
        },
        purple: {
          50: 'var(--bg-field)',
          100: 'var(--bg-card)',
          200: 'var(--border-primary)',
          300: 'var(--border-primary)',
          400: 'var(--color-highlight)',
          500: 'var(--color-primary)',
          600: 'var(--color-primary)',
          700: 'var(--text-secondary)',
          800: 'var(--text-primary)',
          900: 'var(--bg-dark)',
          950: 'var(--bg-dark)',
        },
        violet: {
          50: 'var(--bg-field)',
          100: 'var(--bg-card)',
          200: 'var(--border-primary)',
          300: 'var(--border-primary)',
          400: 'var(--color-highlight)',
          500: 'var(--color-primary)',
          600: 'var(--color-primary)',
          700: 'var(--text-secondary)',
          800: 'var(--text-primary)',
          900: 'var(--bg-dark)',
          950: 'var(--bg-dark)',
        },
        pink: {
          50: 'var(--bg-field)',
          100: 'var(--bg-card)',
          200: 'var(--border-primary)',
          300: 'var(--border-primary)',
          400: 'var(--color-highlight)',
          500: 'var(--color-primary)',
          600: 'var(--color-primary)',
          700: 'var(--text-secondary)',
          800: 'var(--text-primary)',
          900: 'var(--bg-dark)',
          950: 'var(--bg-dark)',
        },
        neutral: {
          50: 'var(--bg-field)',
          100: 'var(--bg-card)',
          200: 'var(--border-primary)',
          300: 'var(--border-primary)',
          400: 'var(--color-highlight)',
          500: 'var(--text-secondary)',
          600: 'var(--text-secondary)',
          700: 'var(--text-primary)',
          800: 'var(--text-primary)',
          900: 'var(--bg-dark)',
          950: 'var(--bg-dark)',
        },
        slate: {
          50: 'var(--bg-field)',
          100: 'var(--bg-card)',
          200: 'var(--border-primary)',
          300: 'var(--border-primary)',
          400: 'var(--color-highlight)',
          500: 'var(--text-secondary)',
          600: 'var(--text-secondary)',
          700: 'var(--text-primary)',
          800: 'var(--text-primary)',
          900: 'var(--bg-dark)',
          950: 'var(--bg-dark)',
        },
        gray: {
          50: 'var(--bg-field)',
          100: 'var(--bg-card)',
          200: 'var(--border-primary)',
          300: 'var(--border-primary)',
          400: 'var(--color-highlight)',
          500: 'var(--text-secondary)',
          600: 'var(--text-secondary)',
          700: 'var(--text-primary)',
          800: 'var(--text-primary)',
          900: 'var(--bg-dark)',
          950: 'var(--bg-dark)',
        },
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        display: ["Inter", "system-ui", "sans-serif"],
      },
      backgroundImage: {
        "page-gradient":
          "linear-gradient(135deg, #f0f4ff 0%, #faf5ff 40%, #f0fdf4 100%)",
        "hero-gradient":
          "linear-gradient(135deg, #4f46e5 0%, #7c3aed 50%, #c026d3 100%)",
        "card-gradient":
          "linear-gradient(135deg, rgba(99,102,241,0.08) 0%, rgba(168,85,247,0.05) 100%)",
      },
      boxShadow: {
        soft: "0 4px 6px -1px rgba(0,0,0,0.05), 0 2px 4px -1px rgba(0,0,0,0.03)",
        glow: "0 0 20px rgba(99, 102, 241, 0.35)",
        "glow-sm": "0 0 10px rgba(99, 102, 241, 0.2)",
        card: "0 10px 15px -3px rgba(0,0,0,0.06), 0 4px 6px -2px rgba(0,0,0,0.03)",
        glass: "0 8px 32px 0 rgba(99, 102, 241, 0.08)",
        premium: "0 20px 60px -10px rgba(79, 70, 229, 0.25), 0 4px 20px -4px rgba(0,0,0,0.08)",
      },
      animation: {
        "fade-in": "fadeIn 0.5s ease-out",
        "slide-up": "slideUp 0.5s ease-out",
        "float": "float 3s ease-in-out infinite",
        "pulse-subtle": "pulseSubtle 2s ease-in-out infinite",
        "shimmer": "shimmer 2s linear infinite",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideUp: {
          "0%": { transform: "translateY(20px)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-10px)" },
        },
        pulseSubtle: {
          "0%, 100%": { opacity: "1", transform: "scale(1)" },
          "50%": { opacity: "0.8", transform: "scale(0.98)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
      },
    },
  },
  plugins: [],
};
