module.exports = {
  darkMode: 'class',
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: 'var(--color-primary)',
          50: 'var(--bg-field)',
          100: 'var(--bg-card)',
          200: 'var(--border-primary)',
          300: 'var(--border-primary)',
          400: 'var(--color-highlight)',
          500: 'var(--color-primary)',
          600: 'var(--color-primary)',
          700: 'var(--text-secondary)',
          800: 'var(--text-primary)',
          900: 'var(--text-primary)',
          950: 'var(--text-primary)',
        },
        secondary: {
          DEFAULT: 'var(--color-highlight)',
          50: 'var(--bg-field)',
          100: 'var(--bg-card)',
          200: 'var(--border-primary)',
          300: 'var(--border-primary)',
          400: 'var(--color-highlight)',
          500: 'var(--color-highlight)',
          600: 'var(--color-accent)',
          700: 'var(--text-secondary)',
          800: 'var(--text-primary)',
          900: 'var(--text-primary)',
          950: 'var(--text-primary)',
        },
        accent: {
          DEFAULT: 'var(--color-accent)',
          50: 'var(--bg-field)',
          100: 'var(--bg-card)',
          200: 'var(--border-primary)',
          300: 'var(--border-primary)',
          400: 'var(--color-highlight)',
          500: 'var(--color-accent)',
          600: 'var(--color-accent)',
          700: 'var(--text-secondary)',
          800: 'var(--text-primary)',
          900: 'var(--text-primary)',
          950: 'var(--text-primary)',
        },
        surface: {
          light: 'var(--color-bg-card-light)',
          dark: 'var(--color-bg-card-dark)',
          "glass-light": "var(--color-bg-card-light)",
          "glass-dark": "var(--color-bg-card-dark)",
        },
        blue: {
          50: 'var(--bg-field)',
          100: 'var(--bg-card)',
          200: 'var(--border-primary)',
          300: 'var(--border-primary)',
          400: 'var(--color-highlight)',
          500: 'var(--color-primary)',
          600: 'var(--color-primary)',
          700: 'var(--text-secondary)',
          800: 'var(--text-primary)',
          900: 'var(--bg-dark)',
          950: 'var(--bg-dark)',
        },
        indigo: {
          50: 'var(--bg-field)',
          100: 'var(--bg-card)',
          200: 'var(--border-primary)',
          300: 'var(--border-primary)',
          400: 'var(--color-highlight)',
          500: 'var(--color-primary)',
          600: 'var(--color-primary)',
          700: 'var(--text-secondary)',
          800: 'var(--text-primary)',
          900: 'var(--bg-dark)',
          950: 'var(--bg-dark)',
        },
        purple: {
          50: 'var(--bg-field)',
          100: 'var(--bg-card)',
          200: 'var(--border-primary)',
          300: 'var(--border-primary)',
          400: 'var(--color-highlight)',
          500: 'var(--color-primary)',
          600: 'var(--color-primary)',
          700: 'var(--text-secondary)',
          800: 'var(--text-primary)',
          900: 'var(--bg-dark)',
          950: 'var(--bg-dark)',
        },
        violet: {
          50: 'var(--bg-field)',
          100: 'var(--bg-card)',
          200: 'var(--border-primary)',
          300: 'var(--border-primary)',
          400: 'var(--color-highlight)',
          500: 'var(--color-primary)',
          600: 'var(--color-primary)',
          700: 'var(--text-secondary)',
          800: 'var(--text-primary)',
          900: 'var(--bg-dark)',
          950: 'var(--bg-dark)',
        },
        pink: {
          50: 'var(--bg-field)',
          100: 'var(--bg-card)',
          200: 'var(--border-primary)',
          300: 'var(--border-primary)',
          400: 'var(--color-highlight)',
          500: 'var(--color-primary)',
          600: 'var(--color-primary)',
          700: 'var(--text-secondary)',
          800: 'var(--text-primary)',
          900: 'var(--bg-dark)',
          950: 'var(--bg-dark)',
        },
        neutral: {
          50: 'var(--bg-field)',
          100: 'var(--bg-card)',
          200: 'var(--border-primary)',
          300: 'var(--border-primary)',
          400: 'var(--color-highlight)',
          500: 'var(--text-secondary)',
          600: 'var(--text-secondary)',
          700: 'var(--text-primary)',
          800: 'var(--text-primary)',
          900: 'var(--bg-dark)',
          950: 'var(--bg-dark)',
        },
        slate: {
          50: 'var(--bg-field)',
          100: 'var(--bg-card)',
          200: 'var(--border-primary)',
          300: 'var(--border-primary)',
          400: 'var(--color-highlight)',
          500: 'var(--text-secondary)',
          600: 'var(--text-secondary)',
          700: 'var(--text-primary)',
          800: 'var(--text-primary)',
          900: 'var(--bg-dark)',
          950: 'var(--bg-dark)',
        },
        gray: {
          50: 'var(--bg-field)',
          100: 'var(--bg-card)',
          200: 'var(--border-primary)',
          300: 'var(--border-primary)',
          400: 'var(--color-highlight)',
          500: 'var(--text-secondary)',
          600: 'var(--text-secondary)',
          700: 'var(--text-primary)',
          800: 'var(--text-primary)',
          900: 'var(--bg-dark)',
          950: 'var(--bg-dark)',
        },
      },
      fontFamily: {
        sans: ["DM Sans", "system-ui", "sans-serif"],
        display: ["Outfit", "system-ui", "sans-serif"],
      },
      backgroundImage: {
        "page-gradient": "none",
        "hero-gradient":
          "linear-gradient(135deg, #0a4f4a 0%, #0f6b63 100%)",
        "card-gradient": "none",
      },
      boxShadow: {
        soft: "0 1px 3px rgba(20,32,30,0.06), 0 1px 2px rgba(20,32,30,0.04)",
        glow: "0 0 0 3px rgba(15, 107, 99, 0.18)",
        "glow-sm": "0 0 0 2px rgba(15, 107, 99, 0.14)",
        card: "0 1px 3px rgba(20,32,30,0.08), 0 1px 2px rgba(20,32,30,0.04)",
        glass: "0 1px 3px rgba(20,32,30,0.06)",
        premium: "0 4px 12px rgba(20,32,30,0.08)",
      },
      animation: {
        "fade-in": "fadeIn 0.45s ease-out",
        "slide-up": "slideUp 0.45s ease-out",
        "float": "float 3s ease-in-out infinite",
        "pulse-subtle": "pulseSubtle 2s ease-in-out infinite",
        "shimmer": "shimmer 2s linear infinite",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideUp: {
          "0%": { transform: "translateY(16px)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-8px)" },
        },
        pulseSubtle: {
          "0%, 100%": { opacity: "1", transform: "scale(1)" },
          "50%": { opacity: "0.85", transform: "scale(0.99)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
      },
    },
  },
  plugins: [],
};
