# Generated by Django 4.2.7 on 2026-05-29 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0001_initial'),
        ('users', '0016_staffactivitylog_staff_activ_user_id_f4153c_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, help_text='In Celsius', max_digits=4, null=True)),
                ('blood_pressure_systolic', models.PositiveIntegerField(blank=True, null=True)),
                ('blood_pressure_diastolic', models.PositiveIntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=1, help_text='In kg', max_digits=5, null=True)),
                ('spo2', models.PositiveIntegerField(blank=True, help_text='Blood oxygen percentage', null=True)),
                ('triage_notes', models.TextField(blank=True)),
                ('symptoms', models.TextField(blank=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('treatment_plan', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for Triage'), ('triage', 'In Triage'), ('consultation', 'In Consultation'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='waiting', max_length=20)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultations', to='users.branch')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='patients.patient')),
                ('practitioner', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['pharmacist', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_consultations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clinical_consultations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=100)),
                ('result', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('performed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='clinical.consultation')),
            ],
            options={
                'db_table': 'clinical_lab_tests',
            },
        ),
    ]
