# Generated by Django 4.2.7 on 2026-05-29 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0014_import_activehours'),
        ('products', '0014_populate_branch_stock'),
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_templates', to='users.branch', verbose_name='Branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_order_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order Template',
                'verbose_name_plural': 'Order Templates',
                'db_table': 'order_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_quantity', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_items', to='products.product')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.ordertemplate')),
            ],
            options={
                'verbose_name': 'Order Template Item',
                'verbose_name_plural': 'Order Template Items',
                'db_table': 'order_template_items',
            },
        ),
    ]
