# Generated by Django 4.2.7

import os
import re
from django.db import migrations

def parse_inserts(filepath, table_name):
    rows = []
    pattern = re.compile(
        rf"INSERT\s+INTO\s+`?{re.escape(table_name)}`?\s+VALUES\s*",
        re.IGNORECASE,
    )
    if not os.path.exists(filepath):
        return rows

    with open(filepath, "r", encoding="latin1") as f:
        for line in f:
            if not pattern.match(line):
                continue
            _, _, values_part = line.partition("VALUES")
            values_part = values_part.strip().rstrip(";").strip()
            rows.extend(_split_value_tuples(values_part))
    return rows

def _split_value_tuples(values_str):
    tuples = []
    depth = 0
    current = []
    i = 0
    while i < len(values_str):
        ch = values_str[i]
        if ch == "(" and depth == 0:
            depth = 1
            current = []
        elif ch == "(" and depth > 0:
            depth += 1
            current.append(ch)
        elif ch == ")" and depth == 1:
            depth = 0
            tuples.append("".join(current))
        elif ch == ")" and depth > 1:
            depth -= 1
            current.append(ch)
        elif ch == "'" and depth > 0:
            j = i + 1
            parts = ["'"]
            while j < len(values_str):
                c = values_str[j]
                parts.append(c)
                if c == "\\" and j + 1 < len(values_str):
                    parts.append(values_str[j + 1])
                    j += 2
                    continue
                if c == "'":
                    if j + 1 < len(values_str) and values_str[j + 1] == "'":
                        parts.append("'")
                        j += 2
                        continue
                    break
                j += 1
            current.append("".join(parts))
            i = j
        elif depth > 0:
            current.append(ch)
        i += 1
    return tuples

def parse_tuple_values(tuple_str):
    values = []
    i = 0
    s = tuple_str
    while i < len(s):
        ch = s[i]
        if ch in (" ", "\t"):
            i += 1
            continue
        if ch == ",":
            i += 1
            continue
        if ch == "'":
            j = i + 1
            parts = []
            while j < len(s):
                c = s[j]
                if c == "\\":
                    if j + 1 < len(s):
                        nc = s[j + 1]
                        if nc == "'": parts.append("'")
                        elif nc == "\\": parts.append("\\")
                        elif nc == "n": parts.append("\n")
                        elif nc == "r": parts.append("\r")
                        elif nc == "t": parts.append("\t")
                        else: parts.append(nc)
                        j += 2
                        continue
                if c == "'":
                    if j + 1 < len(s) and s[j + 1] == "'":
                        parts.append("'")
                        j += 2
                        continue
                    break
                parts.append(c)
                j += 1
            values.append("".join(parts))
            i = j + 1
        elif s[i : i + 4].upper() == "NULL":
            values.append(None)
            i += 4
        else:
            j = i
            while j < len(s) and s[j] not in (",", ")"):
                j += 1
            token = s[i:j].strip()
            try:
                if "." in token: values.append(float(token))
                else: values.append(int(token))
            except ValueError:
                values.append(token)
            i = j
    return values

def import_customer_templates(apps, schema_editor):
    User = apps.get_model('users', 'User')
    Branch = apps.get_model('users', 'Branch')
    Product = apps.get_model('products', 'Product')
    OrderTemplate = apps.get_model('orders', 'OrderTemplate')
    OrderTemplateItem = apps.get_model('orders', 'OrderTemplateItem')

    admin_user = User.objects.filter(is_superuser=True).first()
    if not admin_user:
        admin_user = User.objects.filter(role='admin').first()
        
    main_branch = Branch.objects.filter(name="Transcounty Main").first()

    if not admin_user or not main_branch:
        return
        
    sql_file = "/home/steve/pharmacy-aggregator/database/transcount.sql"
    rows = parse_inserts(sql_file, "customer_template")
    
    # customer_template has columns: id, company, customer, productname, qty
    templates_dict = {}
    
    for row_str in rows:
        vals = parse_tuple_values(row_str)
        if len(vals) < 5:
            continue
            
        _, company, customer, productname, qty = vals[:5]
        
        # We group by company + customer
        key = (company or "", customer or "")
        
        if key not in templates_dict:
            templates_dict[key] = {
                "company_name": str(company) if company else "",
                "customer_name": str(customer) if customer else "Unknown Customer",
                "items": []
            }
            
        templates_dict[key]["items"].append({
            "product_name": str(productname).strip() if productname else "",
            "quantity": float(qty) if qty else 1.0
        })
        
    for key, data in templates_dict.items():
        if not data["items"]:
            continue
            
        template = OrderTemplate.objects.create(
            branch=main_branch,
            created_by=admin_user,
            customer_name=data["customer_name"],
            company_name=data["company_name"],
            is_active=True
        )
        
        for item_data in data["items"]:
            product_name = item_data["product_name"]
            if not product_name:
                continue
                
            product = Product.objects.filter(name__iexact=product_name).first()
            if product:
                OrderTemplateItem.objects.create(
                    template=template,
                    product=product,
                    default_quantity=item_data["quantity"]
                )

def reverse_import(apps, schema_editor):
    OrderTemplate = apps.get_model('orders', 'OrderTemplate')
    OrderTemplate.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_ordertemplate_ordertemplateitem'),
    ]

    operations = [
        migrations.RunPython(import_customer_templates, reverse_import),
    ]
