# Generated by Django 4.2.7 on 2026-06-10 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0005_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_order_templates', to=settings.AUTH_USER_MODEL),
        ),
    ]
