# Generated by Django 4.2.7 on 2026-06-10 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_user_last_activity'),
        ('orders', '0006_alter_ordertemplate_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='users.branch', verbose_name='Branch'),
        ),
    ]
