# Generated by Django 4.2.7 on 2025-10-02 20:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Product Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("pain_relief", "Pain Relief"),
                            ("antibiotics", "Antibiotics"),
                            ("vitamins", "Vitamins & Supplements"),
                            ("chronic_care", "Chronic Care"),
                            ("dermatology", "Dermatology"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Category",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Price (KES)",
                    ),
                ),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Stock Quantity"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="product_images/",
                        verbose_name="Product Image",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "db_table": "products",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="products_name_6f9890_idx"),
                    models.Index(
                        fields=["category"], name="products_categor_fce6e6_idx"
                    ),
                    models.Index(fields=["price"], name="products_price_fe467e_idx"),
                    models.Index(
                        fields=["name", "category"], name="products_name_d3897f_idx"
                    ),
                ],
            },
        ),
    ]
