# Generated by Django 4.2.7 on 2025-10-29 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_stocklog_product_reorder_threshold_and_more'),
        ('products', 'add_featured_field'),
    ]

    operations = [
    ]
