# Generated by Django 4.2.7 on 2025-10-31 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_merge_20251029_1723'),
        ('products', 'add_expiry_and_supplier'),
    ]

    operations = [
    ]
