# Generated by Django 4.2.7 on 2025-12-05 10:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_merge_20251031_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buying_price', models.DecimalField(decimal_places=2, help_text='Cost price from distributor (Base Price)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('wholesale_price', models.DecimalField(decimal_places=2, editable=False, help_text='Wholesale price (Buying Price × 1.1)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('retail_price', models.DecimalField(decimal_places=2, editable=False, help_text='Retail price (Buying Price × 1.5)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('minimum_wholesale_quantity', models.PositiveIntegerField(default=10, help_text='Minimum quantity required to qualify for wholesale price')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this pricing tier is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(help_text='The product this pricing applies to', on_delete=django.db.models.deletion.CASCADE, related_name='pricing_tier', to='products.product')),
            ],
            options={
                'verbose_name': 'Pricing Tier',
                'verbose_name_plural': 'Pricing Tiers',
                'db_table': 'pricing_tier',
            },
        ),
    ]
