# Generated by Django 4.2.7 on 2025-12-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_pricingtier'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dosage_form',
            field=models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('injection', 'Injection'), ('cream', 'Cream/Ointment'), ('drops', 'Drops'), ('inhaler', 'Inhaler'), ('solution', 'Solution'), ('powder', 'Powder'), ('other', 'Other')], default='other', max_length=20, verbose_name='Dosage Form'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Manufacturer'),
        ),
        migrations.AddField(
            model_name='product',
            name='strength',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Strength (e.g., 500mg)'),
        ),
    ]
