# Generated by Django 4.2.7 on 2025-12-12 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_pharmacy_user_pharmacy'),
        ('products', '0007_product_dosage_form_product_manufacturer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='users.pharmacy', verbose_name='Pharmacy'),
        ),
    ]
