# Generated by Django 4.2.7 on 2026-05-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_pricingtier_retail_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shelf_location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Shelf Location'),
        ),
        migrations.AddField(
            model_name='product',
            name='vat_obligation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='VAT Obligation'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Category'),
        ),
    ]
