# Generated by Django 4.2.7 on 2026-05-29 10:55

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_credit_balance_user_is_credit_customer_and_more'),
        ('products', '0012_product_shelf_location_product_vat_obligation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklog',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='The branch where this stock change occurred', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_logs', to='users.branch', verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Deprecated: Use BranchStock instead.', verbose_name='Global Stock (DEPRECATED)'),
        ),
        migrations.CreateModel(
            name='BranchStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current stock level at this branch', max_digits=15, verbose_name='Stock Quantity')),
                ('reorder_level', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum acceptable stock level before reordering', max_digits=15, verbose_name='Reorder Level')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(help_text='The branch holding this stock', on_delete=django.db.models.deletion.CASCADE, related_name='branch_stocks', to='users.branch')),
                ('product', models.ForeignKey(help_text='The product being stocked', on_delete=django.db.models.deletion.CASCADE, related_name='branch_stocks', to='products.product')),
            ],
            options={
                'verbose_name': 'Branch Stock',
                'verbose_name_plural': 'Branch Stocks',
                'db_table': 'branch_stock',
                'indexes': [models.Index(fields=['product', 'branch'], name='branch_stoc_product_c9f2d4_idx'), models.Index(fields=['quantity'], name='branch_stoc_quantit_aea7b5_idx')],
                'unique_together': {('product', 'branch')},
            },
        ),
    ]
