# Generated by Django 4.2.7 on 2026-05-29 10:56

import os
import re
from decimal import Decimal
from django.db import migrations

def parse_inserts(filepath, table_name):
    rows = []
    pattern = re.compile(
        rf"INSERT\s+INTO\s+`?{re.escape(table_name)}`?\s+VALUES\s*",
        re.IGNORECASE,
    )
    if not os.path.exists(filepath):
        return rows

    with open(filepath, "r", encoding="latin1") as f:
        for line in f:
            if not pattern.match(line):
                continue
            _, _, values_part = line.partition("VALUES")
            values_part = values_part.strip().rstrip(";").strip()
            rows.extend(_split_value_tuples(values_part))
    return rows

def _split_value_tuples(values_str):
    tuples = []
    depth = 0
    current = []
    i = 0
    while i < len(values_str):
        ch = values_str[i]
        if ch == "(" and depth == 0:
            depth = 1
            current = []
        elif ch == "(" and depth > 0:
            depth += 1
            current.append(ch)
        elif ch == ")" and depth == 1:
            depth = 0
            tuples.append("".join(current))
        elif ch == ")" and depth > 1:
            depth -= 1
            current.append(ch)
        elif ch == "'" and depth > 0:
            j = i + 1
            parts = ["'"]
            while j < len(values_str):
                c = values_str[j]
                parts.append(c)
                if c == "\\" and j + 1 < len(values_str):
                    parts.append(values_str[j + 1])
                    j += 2
                    continue
                if c == "'":
                    if j + 1 < len(values_str) and values_str[j + 1] == "'":
                        parts.append("'")
                        j += 2
                        continue
                    break
                j += 1
            current.append("".join(parts))
            i = j
        elif depth > 0:
            current.append(ch)
        i += 1
    return tuples

def parse_tuple_values(tuple_str):
    values = []
    i = 0
    s = tuple_str
    while i < len(s):
        ch = s[i]
        if ch in (" ", "\t"):
            i += 1
            continue
        if ch == ",":
            i += 1
            continue
        if ch == "'":
            j = i + 1
            parts = []
            while j < len(s):
                c = s[j]
                if c == "\\":
                    if j + 1 < len(s):
                        nc = s[j + 1]
                        if nc == "'": parts.append("'")
                        elif nc == "\\": parts.append("\\")
                        elif nc == "n": parts.append("\n")
                        elif nc == "r": parts.append("\r")
                        elif nc == "t": parts.append("\t")
                        else: parts.append(nc)
                        j += 2
                        continue
                if c == "'":
                    if j + 1 < len(s) and s[j + 1] == "'":
                        parts.append("'")
                        j += 2
                        continue
                    break
                parts.append(c)
                j += 1
            values.append("".join(parts))
            i = j + 1
        elif s[i : i + 4].upper() == "NULL":
            values.append(None)
            i += 4
        else:
            j = i
            while j < len(s) and s[j] not in (",", ")"):
                j += 1
            token = s[i:j].strip()
            try:
                if "." in token: values.append(float(token))
                else: values.append(int(token))
            except ValueError:
                values.append(token)
            i = j
    return values

def populate_branch_stocks(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    BranchStock = apps.get_model('products', 'BranchStock')
    Branch = apps.get_model('users', 'Branch')
    
    # Pre-fetch branches
    branches = {
        "Transcounty Main": Branch.objects.filter(name="Transcounty Main").first(),
        "Transcounty Annex": Branch.objects.filter(name="Transcounty Annex").first(),
        "Peakfarm": Branch.objects.filter(name="Peakfarm").first(),
    }
    
    if not branches["Transcounty Main"]:
        # If no branches exist, this is likely a test db. Just skip.
        return

    sql_file = "/home/steve/pharmacy-aggregator/database/transcount.sql"
    rows = parse_inserts(sql_file, "unitsofmeasure")
    
    # Store parsed legacy quantities by product name
    legacy_stock = {}
    for row_str in rows:
        vals = parse_tuple_values(row_str)
        if len(vals) < 18:
            continue
        product_name = str(vals[3]).strip() if vals[3] else ""
        if not product_name:
            continue
        stock_main = max(0, int(vals[15] or 0)) if vals[15] is not None else 0
        stock_annex = max(0, int(vals[16] or 0)) if vals[16] is not None else 0
        stock_peak = max(0, int(vals[17] or 0)) if vals[17] is not None else 0
        
        legacy_stock[product_name.lower()] = {
            "Transcounty Main": Decimal(str(stock_main)),
            "Transcounty Annex": Decimal(str(stock_annex)),
            "Peakfarm": Decimal(str(stock_peak))
        }

    branch_stock_objects = []
    
    for product in Product.objects.all():
        name_lower = product.name.lower()
        stocks = legacy_stock.get(name_lower)
        
        if stocks:
            for branch_name, branch_obj in branches.items():
                if branch_obj:
                    branch_stock_objects.append(BranchStock(
                        product=product,
                        branch=branch_obj,
                        quantity=stocks[branch_name],
                        reorder_level=Decimal(str(product.reorder_threshold))
                    ))
        else:
            # Fallback if product not in legacy DB for some reason: 
            # put all stock in main branch
            if branches["Transcounty Main"]:
                branch_stock_objects.append(BranchStock(
                    product=product,
                    branch=branches["Transcounty Main"],
                    quantity=Decimal(str(product.stock_quantity)),
                    reorder_level=Decimal(str(product.reorder_threshold))
                ))
                
    if branch_stock_objects:
        BranchStock.objects.bulk_create(branch_stock_objects, ignore_conflicts=True)


def reverse_populate(apps, schema_editor):
    BranchStock = apps.get_model('products', 'BranchStock')
    BranchStock.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_stocklog_branch_alter_product_stock_quantity_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_branch_stocks, reverse_populate),
    ]
