# Generated by Django 4.2.7 on 2026-06-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_populate_branch_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingtier',
            name='use_legacy_prices',
            field=models.BooleanField(default=False, help_text='If set, do not recalculate wholesale/retail prices from buying_price'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='product',
                    name='is_featured',
                    field=models.BooleanField(default=False, verbose_name='Is Featured'),
                ),
                migrations.AddField(
                    model_name='product',
                    name='shelf_location',
                    field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Shelf Location'),
                ),
                migrations.AddField(
                    model_name='product',
                    name='vat_obligation',
                    field=models.CharField(blank=True, max_length=50, null=True, verbose_name='VAT Obligation'),
                ),
            ],
        ),
    ]
