# Generated by Django 4.2.7 on 2026-06-04 17:51
# This migration creates the department field in Django state
# The database column already exists in production Supabase from manual migration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_pricingtier_use_legacy_prices_product_is_featured_and_more'),
    ]

    operations = [
        # Add field in Django state only (SeparateDatabaseAndState)
        # The actual database column already exists from Supabase migration 20260605
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='product',
                    name='department',
                    field=models.CharField(
                        choices=[('CHEMIST', 'Chemist'), ('AGROVET', 'Agrovet'), ('OTHER', 'Other')],
                        default='OTHER',
                        help_text='Pharmacy department: CHEMIST or AGROVET',
                        max_length=50,
                        verbose_name='Department',
                        db_index=True
                    ),
                ),
                migrations.AddIndex(
                    model_name='product',
                    index=models.Index(fields=['department'], name='products_departm_e701b2_idx'),
                ),
            ],
            database_operations=[
                # No database operations - column already exists
            ],
        ),
    ]
