# Generated by Django 4.2.7 on 2026-06-04 17:51
# Adds Product.department.
#
# Originally this was state-only (SeparateDatabaseAndState with empty
# database_operations) because the column already existed in production Supabase
# from a manual migration. That kept production working but meant a database
# built purely from migrations never got the column, so every fresh environment
# -- including the CI test database -- failed on the next migration (0017 reads
# product.department) with "column products.department does not exist".
#
# Now the column is created only when it is genuinely absent, so this is correct
# in both directions: a no-op on production where it already exists, and a real
# ALTER TABLE on a fresh database.

from django.db import migrations, models


def _department_field():
    return models.CharField(
        choices=[('CHEMIST', 'Chemist'), ('AGROVET', 'Agrovet'), ('OTHER', 'Other')],
        default='OTHER',
        help_text='Pharmacy department: CHEMIST or AGROVET',
        max_length=50,
        verbose_name='Department',
        db_index=True,
    )


def add_department_if_missing(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    connection = schema_editor.connection

    with connection.cursor() as cursor:
        existing = {
            column.name
            for column in connection.introspection.get_table_description(
                cursor, Product._meta.db_table
            )
        }

    if 'department' not in existing:
        field = _department_field()
        field.set_attributes_from_name('department')
        schema_editor.add_field(Product, field)


def noop_reverse(apps, schema_editor):
    """Leave the column in place.

    Dropping it would destroy production data that predates this migration.
    """


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_pricingtier_use_legacy_prices_product_is_featured_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='product',
                    name='department',
                    field=_department_field(),
                ),
                migrations.AddIndex(
                    model_name='product',
                    index=models.Index(fields=['department'], name='products_departm_e701b2_idx'),
                ),
            ],
            database_operations=[
                # Create the column only when it is missing. Production already
                # has it from the Supabase 20260605 migration, so this is a
                # no-op there but a real ALTER TABLE on a fresh database.
                migrations.RunPython(add_department_if_missing, reverse_code=noop_reverse),
            ],
        ),
    ]
