# Generated by Django 4.2.7 on 2026-06-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_pricingtier_use_legacy_prices_product_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='department',
            field=models.CharField(choices=[('CHEMIST', 'Chemist'), ('AGROVET', 'Agrovet'), ('OTHER', 'Other')], default='OTHER', help_text='Pharmacy department: CHEMIST or AGROVET', max_length=50, verbose_name='Department'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['department'], name='products_departm_e701b2_idx'),
        ),
    ]
