# Generated by Django 4.2.7 on 2026-06-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_retry_import_legacy_prices_and_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='department',
            field=models.CharField(choices=[('CHEMIST', 'Chemist'), ('AGROVET', 'Agrovet'), ('OTHER', 'Other')], default='OTHER', help_text='Pharmacy department: CHEMIST or AGROVET', max_length=50, verbose_name='Department'),
        ),
    ]
