# Generated by Django 4.2.7 on 2026-06-07 20:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_product_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingtier',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, help_text='Retail price (Buying Price × 1.33)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pricingtier',
            name='wholesale_price',
            field=models.DecimalField(decimal_places=2, help_text='Wholesale price (Buying Price × 1.15)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
