# Generated by Django 4.2.7 on 2026-06-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_pricingtier_retail_price_and_more'),
    ]

    operations = [
        # Explicitly drop the PostgreSQL check constraints first
        # (PositiveIntegerField adds a CHECK (value >= 0) constraint that must be dropped manually)
        migrations.RunSQL(
            sql=[
                "ALTER TABLE stock_logs DROP CONSTRAINT IF EXISTS stock_logs_previous_quantity_check;",
                "ALTER TABLE stock_logs DROP CONSTRAINT IF EXISTS stock_logs_new_quantity_check;",
            ],
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='stocklog',
            name='new_quantity',
            field=models.IntegerField(verbose_name='New Quantity'),
        ),
        migrations.AlterField(
            model_name='stocklog',
            name='previous_quantity',
            field=models.IntegerField(verbose_name='Previous Quantity'),
        ),
    ]
