# Generated by Django 4.2.7 on 2026-06-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_branchstock_quantity_non_negative'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='branchstock',
            index=models.Index(fields=['branch', 'quantity'], name='bs_branch_qty_idx'),
        ),
    ]
