# Generated by Django 4.2.7 on 2026-07-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_perf_add_indexes_dispensation_branchstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('CHEMIST', 'Chemist/Pharmacy Product'), ('AGROVET', 'Agrovet Product'), ('UNIVERSAL', 'Universal (both)')], db_index=True, default='CHEMIST', help_text='Determines which branch types can see and sell this product', max_length=20),
        ),
    ]
