# Generated by Django 4.2.7 on 2025-11-04 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispensingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity Dispensed')),
                ('previous_stock', models.PositiveIntegerField(verbose_name='Stock Before Dispensing')),
                ('new_stock', models.PositiveIntegerField(verbose_name='Stock After Dispensing')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Cost (KES)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Additional Notes')),
                ('dispensed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispensing_logs', to=settings.AUTH_USER_MODEL, verbose_name='Dispensed By')),
            ],
            options={
                'verbose_name': 'Dispensing Log',
                'verbose_name_plural': 'Dispensing Logs',
                'db_table': 'dispensing_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
