# Generated by Django 4.2.7 on 2025-11-04 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispensing_logs', '0001_initial'),
        ('products', '0005_make_pharmacy_optional'),
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispensinglog',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispensing_logs', to='orders.order', verbose_name='Related Order'),
        ),
        migrations.AddField(
            model_name='dispensinglog',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispensing_logs', to='products.product', verbose_name='Product'),
        ),
        migrations.AddIndex(
            model_name='dispensinglog',
            index=models.Index(fields=['created_at'], name='dispensing__created_58c75f_idx'),
        ),
        migrations.AddIndex(
            model_name='dispensinglog',
            index=models.Index(fields=['product', 'created_at'], name='dispensing__product_5807d2_idx'),
        ),
        migrations.AddIndex(
            model_name='dispensinglog',
            index=models.Index(fields=['dispensed_by', 'created_at'], name='dispensing__dispens_df52ee_idx'),
        ),
    ]
