# Generated by Django 4.2.7 on 2026-06-10 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dispensing_logs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispensinglog',
            name='dispensed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensing_logs', to=settings.AUTH_USER_MODEL, verbose_name='Dispensed By'),
        ),
    ]
