import io
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4, letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image
from reportlab.lib.enums import TA_CENTER, TA_RIGHT
from django.conf import settings
from datetime import datetime

class PDFGenerator:
    """
    Utility class for generating PDFs for receipts, invoices, and reports.
    """
    
    def __init__(self, buffer=None):
        self.buffer = buffer or io.BytesIO()
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()

    def _setup_custom_styles(self):
        """Setup custom styles for the documents."""
        self.styles.add(ParagraphStyle(
            name='CenterHeader',
            parent=self.styles['Heading1'],
            alignment=TA_CENTER,
            fontSize=16,
            spaceAfter=12
        ))
        self.styles.add(ParagraphStyle(
            name='CenterSubHeader',
            parent=self.styles['Heading2'],
            alignment=TA_CENTER,
            fontSize=12,
            spaceAfter=10,
            textColor=colors.grey
        ))
        self.styles.add(ParagraphStyle(
            name='RightText',
            parent=self.styles['Normal'],
            alignment=TA_RIGHT
        ))
        self.styles.add(ParagraphStyle(
            name='BoldText',
            parent=self.styles['Normal'],
            fontName='Helvetica-Bold'
        ))

    def generate_receipt(self, order):
        """
        Generate a PDF receipt for a specific order.
        """
        doc = SimpleDocTemplate(self.buffer, pagesize=A4, rightMargin=72, leftMargin=72, topMargin=72, bottomMargin=18)
        elements = []

        # Header
        elements.append(Paragraph("TRANSCOUNTY PHARMACY AGGREGATOR", self.styles['CenterHeader']))
        elements.append(Paragraph(f"Official Receipt - Order #{order.id}", self.styles['CenterSubHeader']))
        elements.append(Spacer(1, 0.2 * inch))

        # Order Details (Meta)
        meta_data = [
            [Paragraph(f"<b>Date:</b> {order.created_at.strftime('%Y-%m-%d %H:%M')}", self.styles['Normal']), 
             Paragraph(f"<b>Generated By:</b> {order.user.get_full_name() or order.user.username}", self.styles['RightText'])],
            [Paragraph(f"<b>Status:</b> {order.status.upper()}", self.styles['Normal']), 
             Paragraph(f"<b>Reference:</b> CASH-{order.id}", self.styles['RightText'])]
        ]
        meta_table = Table(meta_data, colWidths=[3 * inch, 3.5 * inch])
        elements.append(meta_table)
        elements.append(Spacer(1, 0.3 * inch))

        # Items Table
        items_data = [['Product', 'Quantity', 'Unit Price', 'Subtotal']]
        for item in order.items.all():
            items_data.append([
                item.product.name,
                str(item.quantity),
                f"KES {item.unit_price:,.2f}",
                f"KES {item.subtotal:,.2f}"
            ])
        
        items_data.append(['', '', 'TOTAL', f"KES {order.total_amount:,.2f}"])

        table = Table(items_data, colWidths=[3 * inch, 1 * inch, 1.25 * inch, 1.25 * inch])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.indigo),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('ALIGN', (1, 1), (-1, -1), 'RIGHT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, -1), (-1, -1), colors.beige),
            ('FONTNAME', (2, -1), (3, -1), 'Helvetica-Bold'),
            ('GRID', (0, 0), (-1, -2), 0.5, colors.grey),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ]))
        elements.append(table)
        elements.append(Spacer(1, 0.5 * inch))

        # Footer
        elements.append(Paragraph("Thank you for your business!", self.styles['CenterSubHeader']))
        elements.append(Paragraph("This is a computer-generated receipt.", self.styles['CenterSubHeader']))

        doc.build(elements)
        self.buffer.seek(0)
        return self.buffer

    def generate_analytics_report(self, data, title="Analytics Report"):
        """
        Generate a summary PDF report from analytics data.
        """
        doc = SimpleDocTemplate(self.buffer, pagesize=A4)
        elements = []

        elements.append(Paragraph("TRANSCOUNTY PHARMACY", self.styles['CenterHeader']))
        elements.append(Paragraph(title, self.styles['CenterSubHeader']))
        elements.append(Paragraph(f"Generated on {datetime.now().strftime('%Y-%m-%d %H:%M')}", self.styles['RightText']))
        elements.append(Spacer(1, 0.3 * inch))

        for section_title, section_data in data.items():
            elements.append(Paragraph(section_title, self.styles['Heading2']))
            elements.append(Spacer(1, 0.1 * inch))
            
            if isinstance(section_data, list) and len(section_data) > 0:
                # Assuming list of dicts for table
                headers = list(section_data[0].keys())
                table_data = [headers]
                for row in section_data:
                    table_data.append([str(row.get(h, "")) for h in headers])
                
                t = Table(table_data, hAlign='LEFT')
                t.setStyle(TableStyle([
                    ('BACKGROUND', (0, 0), (-1, 0), colors.lightgrey),
                    ('TEXTCOLOR', (0, 0), (-1, 0), colors.black),
                    ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                    ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                ]))
                elements.append(t)
            else:
                elements.append(Paragraph("No data available for this section.", self.styles['Italic']))
            
            elements.append(Spacer(1, 0.3 * inch))

        doc.build(elements)
        self.buffer.seek(0)
        return self.buffer

    def generate_quotation_pdf(self, data, title="Quotation"):
        doc = SimpleDocTemplate(self.buffer, pagesize=A4, rightMargin=72, leftMargin=72, topMargin=72, bottomMargin=36)
        elements = []

        elements.append(Paragraph("TRANSCOUNTY PHARMACY AGGREGATOR", self.styles['CenterHeader']))
        elements.append(Paragraph(title, self.styles['CenterSubHeader']))
        elements.append(Spacer(1, 0.2 * inch))

        # Meta Data
        meta_data = [
            [Paragraph(f"<b>Customer:</b> {data.get('Customer Name')}", self.styles['Normal']), 
             Paragraph(f"<b>Date:</b> {datetime.now().strftime('%Y-%m-%d')}", self.styles['RightText'])],
            [Paragraph(f"<b>Phone:</b> {data.get('Customer Phone', 'N/A')}", self.styles['Normal']), 
             Paragraph(f"<b>Valid Until:</b> {data.get('Valid Until')}", self.styles['RightText'])],
            [Paragraph(f"<b>Branch:</b> {data.get('Branch')}", self.styles['Normal']), 
             Paragraph(f"<b>Status:</b> {data.get('Status')}", self.styles['RightText'])]
        ]
        meta_table = Table(meta_data, colWidths=[3 * inch, 3.5 * inch])
        elements.append(meta_table)
        elements.append(Spacer(1, 0.3 * inch))

        # Items
        items_data = [['Product', 'Quantity', 'Unit Price', 'Subtotal']]
        for item in data.get("Items", []):
            items_data.append([
                item['Product'],
                str(item['Quantity']),
                f"KES {item['Unit Price']:,.2f}",
                f"KES {item['Subtotal']:,.2f}"
            ])
            
        items_data.append(['', '', 'TOTAL', f"KES {data.get('Total Amount (KES)', 0):,.2f}"])

        table = Table(items_data, colWidths=[3 * inch, 1 * inch, 1.25 * inch, 1.25 * inch])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#0ea5e9')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('ALIGN', (1, 1), (-1, -1), 'RIGHT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, -1), (-1, -1), colors.beige),
            ('FONTNAME', (2, -1), (3, -1), 'Helvetica-Bold'),
            ('GRID', (0, 0), (-1, -2), 0.5, colors.grey),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ]))
        elements.append(table)
        
        elements.append(Spacer(1, 0.5 * inch))
        if data.get("Notes"):
            elements.append(Paragraph("<b>Notes:</b>", self.styles['Normal']))
            elements.append(Paragraph(data.get("Notes"), self.styles['Normal']))
            elements.append(Spacer(1, 0.3 * inch))

        elements.append(Paragraph("Thank you for choosing Transcounty Pharmacy!", self.styles['CenterSubHeader']))
        elements.append(Paragraph(f"This quotation is valid until {data.get('Valid Until')}.", self.styles['CenterSubHeader']))

        doc.build(elements)
        self.buffer.seek(0)
        return self.buffer
