# Generated by Django 4.2.7 on 2025-12-05 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0006_pricingtier'),
        ('inventory', '0002_dispensation_prescription_prescriptionitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distributor_name', models.CharField(help_text='Name of the distributor or supplier', max_length=255)),
                ('quantity_received', models.PositiveIntegerField(help_text='Number of units received')),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Cost per unit from distributor', max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, editable=False, help_text='Total cost (quantity × unit_cost)', max_digits=12)),
                ('expiry_date', models.DateField(blank=True, help_text='Expiry date of the batch', null=True)),
                ('batch_number', models.CharField(blank=True, help_text='Batch/lot number from distributor', max_length=100, null=True)),
                ('received_date', models.DateTimeField(auto_now_add=True, help_text='Date and time when stock was recorded')),
                ('notes', models.TextField(blank=True, help_text='Additional notes (e.g., condition of stock, issues)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(help_text='The product/medicine received', on_delete=django.db.models.deletion.PROTECT, related_name='stock_intakes', to='products.product')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_intakes_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock Intake',
                'verbose_name_plural': 'Stock Intakes',
                'db_table': 'stock_intake',
                'ordering': ['-received_date'],
                'indexes': [models.Index(fields=['product', '-received_date'], name='stock_intak_product_6e110d_idx'), models.Index(fields=['distributor_name', '-received_date'], name='stock_intak_distrib_c43156_idx'), models.Index(fields=['received_date'], name='stock_intak_receive_da30d5_idx')],
            },
        ),
    ]
