# Generated by Django 4.2.7 on 2025-12-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stockintake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispensationitem',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
