# Generated by Django 4.2.7 on 2025-12-11 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_dosage_form_product_manufacturer_and_more'),
        ('inventory', '0004_alter_dispensationitem_expiry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Supplier Name')),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact Person')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone Number')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'db_table': 'suppliers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100, verbose_name='Batch Number')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity')),
                ('expiry_date', models.DateField(verbose_name='Expiry Date')),
                ('received_date', models.DateField(auto_now_add=True, verbose_name='Received Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='products.product', verbose_name='Product')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='inventory.supplier', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
                'db_table': 'batches',
                'ordering': ['expiry_date'],
                'indexes': [models.Index(fields=['product', 'expiry_date'], name='batches_product_fefee9_idx'), models.Index(fields=['batch_number'], name='batches_batch_n_62e6fc_idx')],
            },
        ),
    ]
