# Generated by Django 4.2.7 on 2026-05-22 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_add_branch_model'),
        ('inventory', '0006_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispensation',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='The branch where this sale/dispensation occurred.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispensations', to='users.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='The branch where this prescription was created/verified.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='users.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='restockrequest',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='The branch making this restock request.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='restock_requests', to='users.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='stockintake',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='The branch that received this stock.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_intakes', to='users.branch', verbose_name='Branch'),
        ),
    ]
