# Generated by Django 4.2.7 on 2026-05-29 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0010_user_credit_balance_user_is_credit_customer_and_more'),
        ('products', '0012_product_shelf_location_product_vat_obligation_and_more'),
        ('inventory', '0007_add_branch_fks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Service Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Price')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_services', to='users.branch', verbose_name='Branch')),
            ],
            options={
                'verbose_name': 'Clinical Service',
                'verbose_name_plural': 'Clinical Services',
                'db_table': 'clinical_services',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LegacyLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=255, verbose_name='Account Name')),
                ('debit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Debit')),
                ('credit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Credit')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('branch', models.CharField(blank=True, max_length=255, null=True, verbose_name='Branch Name (Legacy)')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('legacy_id', models.IntegerField(unique=True, verbose_name='Legacy ID')),
            ],
            options={
                'verbose_name': 'Legacy Ledger Entry',
                'verbose_name_plural': 'Legacy Ledger Entries',
                'db_table': 'legacy_ledger_entries',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='dispensation',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Discount'),
        ),
        migrations.AddField(
            model_name='dispensation',
            name='payment_mode',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Payment Mode'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Balance'),
        ),
        migrations.CreateModel(
            name='SoldService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Quantity')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total Price')),
                ('payment_mode', models.CharField(max_length=50, verbose_name='Payment Mode')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('legacy_id', models.IntegerField(blank=True, null=True, verbose_name='Legacy ID')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sold_services', to='users.branch', verbose_name='Branch')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_received', to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
                ('served_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services_provided', to=settings.AUTH_USER_MODEL, verbose_name='Served By')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='inventory.clinicalservice', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Sold Service',
                'verbose_name_plural': 'Sold Services',
                'db_table': 'sold_services',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProductReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_type', models.CharField(choices=[('INWARD', 'Return Inward (From Customer)'), ('OUTWARD', 'Return Outward (To Supplier)')], max_length=20, verbose_name='Return Type')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity')),
                ('reason', models.CharField(max_length=255, verbose_name='Reason for Return')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('legacy_id', models.IntegerField(blank=True, null=True, verbose_name='Legacy ID')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_returns', to='users.branch', verbose_name='Branch')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to=settings.AUTH_USER_MODEL, verbose_name='Customer (For Inwards)')),
                ('processed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processed_returns', to=settings.AUTH_USER_MODEL, verbose_name='Processed By')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='products.product', verbose_name='Product')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='inventory.supplier', verbose_name='Supplier (For Outwards)')),
            ],
            options={
                'verbose_name': 'Product Return',
                'verbose_name_plural': 'Product Returns',
                'db_table': 'product_returns',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SupplierCreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('PURCHASE_ON_CREDIT', 'Purchase on Credit'), ('PAYMENT', 'Payment to Supplier'), ('ADJUSTMENT', 'Balance Adjustment')], max_length=25, verbose_name='Transaction Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Balance After')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Invoice Number')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_supplier_credit_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to='inventory.supplier', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Supplier Credit Transaction',
                'verbose_name_plural': 'Supplier Credit Transactions',
                'db_table': 'supplier_credit_transactions',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['supplier', 'timestamp'], name='supplier_cr_supplie_2f298b_idx'), models.Index(fields=['invoice_number'], name='supplier_cr_invoice_f271f3_idx')],
            },
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netflow', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Net Flow')),
                ('paymentmode', models.CharField(max_length=100, verbose_name='Payment Mode')),
                ('explanation', models.CharField(max_length=255, verbose_name='Explanation')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashflows', to='users.branch', verbose_name='Branch')),
            ],
            options={
                'verbose_name': 'Cash Flow',
                'verbose_name_plural': 'Cash Flows',
                'db_table': 'cashflow',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['branch', 'timestamp'], name='cashflow_branch__51535e_idx')],
            },
        ),
    ]
