# Generated by Django 4.2.7 on 2026-05-29 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_populate_branch_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0014_import_activehours'),
        ('inventory', '0009_interbranchtransfer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicalservice',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='productreturn',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='productreturn',
            name='legacy_id',
        ),
        migrations.RemoveField(
            model_name='productreturn',
            name='processed_by',
        ),
        migrations.RemoveField(
            model_name='productreturn',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='soldservice',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='soldservice',
            name='legacy_id',
        ),
        migrations.RemoveField(
            model_name='soldservice',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='soldservice',
            name='served_by',
        ),
        migrations.RemoveField(
            model_name='soldservice',
            name='total_price',
        ),
        migrations.AddField(
            model_name='clinicalservice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinicalservice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productreturn',
            name='handled_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='handled_returns', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soldservice',
            name='patient_name',
            field=models.CharField(default='unknown', max_length=255, verbose_name='Patient Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soldservice',
            name='sold_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='sold_services', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clinicalservice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='productreturn',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='users.branch'),
        ),
        migrations.AlterField(
            model_name='productreturn',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='products.product'),
        ),
        migrations.AlterField(
            model_name='productreturn',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='productreturn',
            name='reason',
            field=models.TextField(verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='productreturn',
            name='return_type',
            field=models.CharField(choices=[('INWARD', 'Inward (Customer to Pharmacy)'), ('OUTWARD', 'Outward (Pharmacy to Supplier)')], max_length=10, verbose_name='Return Type'),
        ),
        migrations.AlterField(
            model_name='productreturn',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='soldservice',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sold_services', to='users.branch'),
        ),
        migrations.AlterField(
            model_name='soldservice',
            name='payment_mode',
            field=models.CharField(choices=[('CASH', 'Cash'), ('MPESA_TILL', 'M-Pesa Till'), ('EQUITY_TILL', 'Equity Till'), ('NATIONAL_BANK', 'National Bank')], max_length=50, verbose_name='Payment Mode'),
        ),
        migrations.AlterField(
            model_name='soldservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='inventory.clinicalservice'),
        ),
        migrations.AlterField(
            model_name='soldservice',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Timestamp'),
        ),
    ]
