# Generated by Django 4.2.7 on 2026-05-29 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_remove_clinicalservice_branch_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stockintake',
            name='stock_intak_distrib_c43156_idx',
        ),
        migrations.RemoveField(
            model_name='stockintake',
            name='distributor_name',
        ),
        migrations.AddField(
            model_name='stockintake',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Invoice or reference number from the supplier', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stockintake',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('CREDIT', 'Credit'), ('PARTIAL', 'Partial')], default='PAID', help_text='Payment status for this intake', max_length=20),
        ),
        migrations.AddField(
            model_name='stockintake',
            name='supplier',
            field=models.ForeignKey(default=1, help_text='Supplier of the stock', on_delete=django.db.models.deletion.PROTECT, related_name='stock_intakes', to='inventory.supplier'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='stockintake',
            index=models.Index(fields=['supplier', '-received_date'], name='stock_intak_supplie_f1daae_idx'),
        ),
    ]
