# Generated by Django 4.2.7 on 2026-05-29 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0011_remove_stockintake_stock_intak_distrib_c43156_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispensation',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Registered customer for credit tracking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_dispensations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispensation',
            name='pricing_tier',
            field=models.CharField(choices=[('RETAIL', 'Retail'), ('WHOLESALE', 'Wholesale')], default='RETAIL', max_length=20),
        ),
        migrations.AlterField(
            model_name='dispensation',
            name='payment_mode',
            field=models.CharField(choices=[('CASH', 'Cash'), ('MPESA_TILL', 'M-Pesa Till'), ('EQUITY_TILL', 'Equity Till'), ('NATIONAL_BANK', 'National Bank'), ('CREDIT', 'Credit')], default='CASH', max_length=50, verbose_name='Payment Mode'),
        ),
    ]
