# Generated by Django 4.2.7 on 2026-05-29 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0016_staffactivitylog_staff_activ_user_id_f4153c_idx'),
        ('inventory', '0012_dispensation_customer_dispensation_pricing_tier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reason', models.TextField()),
                ('total_refund', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_returns', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_returns', to='users.branch')),
                ('dispensation', models.ForeignKey(help_text='The original sale being returned.', on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='inventory.dispensation')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_returns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SaleReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('condition', models.CharField(choices=[('sellable', 'Sellable (Restock)'), ('damaged', 'Damaged/Expired (Do Not Restock)')], default='sellable', max_length=20)),
                ('dispensation_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='inventory.dispensationitem')),
                ('return_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.salereturn')),
            ],
        ),
    ]
