# Generated by Django 4.2.7 on 2026-06-10 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0014_alter_interbranchtransfer_requested_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispensation',
            name='dispensed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productreturn',
            name='handled_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salereturn',
            name='initiated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='soldservice',
            name='sold_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_services', to=settings.AUTH_USER_MODEL),
        ),
    ]
