# Generated by Django 4.2 on 2026-06-11 16:15
from django.db import migrations
from django.utils import timezone
import logging

logger = logging.getLogger(__name__)

def migrate_pricing_tiers(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    PricingTier = apps.get_model('products', 'PricingTier')
    
    # Migrate products that don't have a pricing tier
    products_without_tiers = Product.objects.filter(pricing_tier__isnull=True)
    count = 0
    for product in products_without_tiers:
        price = product.price if product.price else 0
        PricingTier.objects.create(
            product=product,
            buying_price=price,
            wholesale_price=price,
            retail_price=price,
            use_legacy_prices=True
        )
        count += 1
    
    print(f"\\nMigrated {count} legacy prices to Pricing Tiers.")

def migrate_orders_to_dispensations(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    OrderItem = apps.get_model('orders', 'OrderItem')
    Dispensation = apps.get_model('inventory', 'Dispensation')
    DispensationItem = apps.get_model('inventory', 'DispensationItem')
    Payment = apps.get_model('orders', 'Payment')
    CashFlow = apps.get_model('inventory', 'CashFlow')
    
    # We only migrate delivered or completed orders
    orders_to_migrate = Order.objects.filter(status__in=['delivered', 'completed'])
    count = 0
    
    for order in orders_to_migrate:
        # Check if a dispensation for this order already exists to avoid duplicates
        note_text = f"Migrated from Order #{order.id}"
        if Dispensation.objects.filter(notes__contains=note_text).exists():
            continue
            
        # Figure out payment mode
        payment_mode = 'CASH'
        payment = Payment.objects.filter(order=order).first()
        if payment:
            pm = str(payment.method).upper()
            if 'MPESA' in pm or 'TILL' in pm:
                payment_mode = 'MPESA_TILL'
            elif 'CREDIT' in pm:
                payment_mode = 'CREDIT'
            elif 'BANK' in pm or 'STRIPE' in pm:
                payment_mode = 'NATIONAL_BANK'
                
        dispensation = Dispensation.objects.create(
            sale_type='otc',
            branch=order.branch,
            patient_name=order.patient_name or '',
            customer=order.customer,
            dispensed_by=order.user,
            total_amount=order.total_amount,
            payment_mode=payment_mode,
            pricing_tier='RETAIL',
            notes=note_text
        )
        
        # Django's auto_now_add on dispensed_at might override our custom value during create
        # We must update it after creation
        Dispensation.objects.filter(id=dispensation.id).update(dispensed_at=order.created_at)
        
        items = OrderItem.objects.filter(order=order)
        for item in items:
            DispensationItem.objects.create(
                dispensation=dispensation,
                product=item.product,
                quantity=item.quantity,
                price_per_unit=item.unit_price,
                total_price=item.subtotal,
            )
            
        # Migrate CashFlow records as well so the legacy accounting matches the dashboard
        # Orders never created CashFlow records, they just created Payments
        if payment_mode != 'CREDIT':
            CashFlow.objects.create(
                netflow=order.total_amount,
                paymentmode=payment_mode,
                explanation=f"Sale (Migrated Order #{order.id})",
                branch=order.branch,
                timestamp=order.created_at
            )
            
        count += 1

    print(f"\\nMigrated {count} Orders to Dispensations and generated CashFlows.")


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_dispensation_dispensed_by_and_more'),
        ('products', '0021_alter_pricingtier_retail_price_and_more'),
        ('orders', '0008_order_customer_order_patient_name'),
    ]

    operations = [
        migrations.RunPython(migrate_pricing_tiers, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(migrate_orders_to_dispensations, reverse_code=migrations.RunPython.noop),
    ]
