# Generated by Django 4.2 on 2026-06-11 16:30
from django.db import migrations

def fix_legacy_data(apps, schema_editor):
    Branch = apps.get_model('users', 'Branch')
    first_branch = Branch.objects.first()
    
    # 1. Assign default branch to legacy orders/dispensations/cashflow
    if first_branch:
        Order = apps.get_model('orders', 'Order')
        Dispensation = apps.get_model('inventory', 'Dispensation')
        CashFlow = apps.get_model('inventory', 'CashFlow')
        
        Order.objects.filter(branch__isnull=True).update(branch=first_branch)
        Dispensation.objects.filter(branch__isnull=True).update(branch=first_branch)
        CashFlow.objects.filter(branch__isnull=True).update(branch=first_branch)

    # 2. Fix pricing tiers because 0016 failed to find them due to historical model reverse relation issues
    Product = apps.get_model('products', 'Product')
    PricingTier = apps.get_model('products', 'PricingTier')
    
    existing_tier_product_ids = set(PricingTier.objects.values_list('product_id', flat=True))
    products_without_tiers = [p for p in Product.objects.all() if p.id not in existing_tier_product_ids]
    
    for product in products_without_tiers:
        PricingTier.objects.create(
            product=product,
            buying_price=product.price,
            wholesale_price=product.price * 1.15,
            retail_price=product.price * 1.33,
            use_legacy_prices=True,
            is_active=True
        )

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_auto_migrate_legacy_data'),
        ('users', '0001_initial'),
        ('products', '0021_alter_pricingtier_retail_price_and_more'),
    ]

    operations = [
        migrations.RunPython(fix_legacy_data, reverse_code=migrations.RunPython.noop),
    ]
