# Generated by Django 4.2 on 2026-06-11 16:30
from django.db import migrations

def move_legacy_data_to_main_branch(apps, schema_editor):
    Branch = apps.get_model('users', 'Branch')
    
    # Try to find a branch named "Main Branch" or containing "main"
    main_branch = Branch.objects.filter(name__icontains='main').first()
    
    # If not found, try finding one containing "transcounty"
    if not main_branch:
        main_branch = Branch.objects.filter(name__icontains='transcounty').first()
        
    # If still not found, we don't know which one is the "main" branch, so abort safely.
    if not main_branch:
        # As a fallback, if there are exactly 2 branches and the first is peakfam, use the second
        branches = list(Branch.objects.all()[:2])
        if len(branches) == 2:
            main_branch = branches[1]
        else:
            return
            
    # We only move the records that were incorrectly assigned to the very first branch
    first_branch = Branch.objects.first()
    if not first_branch or first_branch.id == main_branch.id:
        return # already correct
        
    Order = apps.get_model('orders', 'Order')
    Dispensation = apps.get_model('inventory', 'Dispensation')
    CashFlow = apps.get_model('inventory', 'CashFlow')
    
    # Move Orders that belong to the first branch (all legacy orders were moved here)
    Order.objects.filter(branch=first_branch).update(branch=main_branch)
    
    # Move only the Dispensations and CashFlows that were migrated
    Dispensation.objects.filter(
        branch=first_branch, 
        notes__startswith='Migrated from Order #'
    ).update(branch=main_branch)
    
    CashFlow.objects.filter(
        branch=first_branch, 
        explanation__startswith='Sale (Migrated Order #'
    ).update(branch=main_branch)

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_assign_default_branch_to_legacy_data'),
    ]

    operations = [
        migrations.RunPython(move_legacy_data_to_main_branch, reverse_code=migrations.RunPython.noop),
    ]
