# Generated by Django 4.2.7 on 2026-06-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_reassign_legacy_data_to_main_branch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispensation',
            options={'verbose_name': 'Dispensation', 'verbose_name_plural': 'Dispensations'},
        ),
        migrations.AddIndex(
            model_name='dispensation',
            index=models.Index(fields=['branch', 'dispensed_at'], name='disp_branch_date_idx'),
        ),
        migrations.AddIndex(
            model_name='dispensation',
            index=models.Index(fields=['dispensed_at'], name='disp_date_idx'),
        ),
        migrations.AddIndex(
            model_name='dispensation',
            index=models.Index(fields=['customer'], name='disp_customer_idx'),
        ),
    ]
