# Generated by Django 4.2.7 on 2026-06-20 13:40

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def copy_batch_quantity(apps, schema_editor):
    Batch = apps.get_model("inventory", "Batch")
    for batch in Batch.objects.all():
        qty = getattr(batch, "quantity", 0) or 0
        batch.quantity_received = Decimal(str(qty))
        batch.quantity_remaining = Decimal(str(qty))
        batch.save(update_fields=["quantity_received", "quantity_remaining"])


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0023_supplier_intelligence_and_batch_fefo"),
        ("products", "0025_perf_add_indexes_dispensation_branchstock"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0019_perf_add_indexes_dispensation_branchstock"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SENT", "Sent"),
                            ("RECEIVED", "Received"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expected_delivery", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("cancellation_reason", models.TextField(blank=True, default="")),
                (
                    "total_estimated_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                    ),
                ),
            ],
            options={
                "db_table": "purchase_orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_ordered",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "estimated_unit_price",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "actual_unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "quantity_received",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "purchase_order_items",
            },
        ),
        migrations.AddField(
            model_name="batch",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="batches",
                to="users.branch",
                verbose_name="Branch",
            ),
        ),
        migrations.AddField(
            model_name="batch",
            name="clearance_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                verbose_name="Clearance Price",
            ),
        ),
        migrations.AddField(
            model_name="batch",
            name="cost_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                verbose_name="Cost Price",
            ),
        ),
        migrations.AddField(
            model_name="batch",
            name="is_clearance",
            field=models.BooleanField(default=False, verbose_name="Is Clearance"),
        ),
        migrations.AddField(
            model_name="batch",
            name="quantity_received",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=15,
                verbose_name="Quantity Received",
            ),
        ),
        migrations.AddField(
            model_name="batch",
            name="quantity_remaining",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=15,
                verbose_name="Quantity Remaining",
            ),
        ),
        migrations.RunPython(copy_batch_quantity, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="batch",
            name="quantity",
        ),
        migrations.AddField(
            model_name="interbranchtransfer",
            name="rejection_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="batch",
            name="batch_number",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="Batch Number",
            ),
        ),
        migrations.AlterField(
            model_name="batch",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="batches",
                to="products.product",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="stockintake",
            name="total_cost",
            field=models.DecimalField(
                decimal_places=2,
                editable=False,
                help_text="Total cost (quantity × unit_cost)",
                max_digits=15,
            ),
        ),
        migrations.AlterField(
            model_name="stockintake",
            name="unit_cost",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Cost per unit from distributor",
                max_digits=15,
            ),
        ),
        migrations.AddIndex(
            model_name="batch",
            index=models.Index(
                fields=["product", "branch", "expiry_date"],
                name="batches_product_671bf8_idx",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_order_items",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="purchase_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="inventory.purchaseorder",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_orders",
                to="users.branch",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_orders_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_orders",
                to="inventory.supplier",
            ),
        ),
    ]
