# Generated by Django 4.2.7 on 2026-07-22 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_classify_products_and_update_branches'),
        ('users', '0023_supplier_intelligence_and_batch_fefo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0020_supplier_intelligence_and_batch_fefo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Client-generated id; the idempotency key for replay.', unique=True)),
                ('op_type', models.CharField(choices=[('sale', 'Sale / dispense'), ('intake', 'Stock intake'), ('adjustment', 'Stock adjustment')], max_length=20)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('duplicate', 'Duplicate (already applied)'), ('conflict', 'Conflict'), ('error', 'Error')], default='applied', max_length=20)),
                ('payload', models.JSONField(default=dict, help_text='The operation as sent by the client.')),
                ('result_ref', models.CharField(blank=True, help_text='Reference to the record created server-side (e.g. dispensation id).', max_length=100)),
                ('error_detail', models.TextField(blank=True)),
                ('had_discrepancy', models.BooleanField(default=False)),
                ('client_created_at', models.DateTimeField(blank=True, help_text='When the client recorded the action offline.', null=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_operations', to='users.branch')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sync_operation',
                'ordering': ['-processed_at'],
            },
        ),
        migrations.CreateModel(
            name='StockDiscrepancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_quantity', models.DecimalField(decimal_places=2, help_text='Stock the server held before applying the operation.', max_digits=15)),
                ('requested_quantity', models.DecimalField(decimal_places=2, help_text='Quantity the operation tried to remove.', max_digits=15)),
                ('oversold_quantity', models.DecimalField(decimal_places=2, help_text='How far past available stock the operation went (requested - expected).', max_digits=15)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_discrepancies', to='users.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_discrepancies', to='products.product')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_discrepancies', to=settings.AUTH_USER_MODEL)),
                ('source_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discrepancies', to='inventory.syncoperation')),
            ],
            options={
                'db_table': 'stock_discrepancy',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='syncoperation',
            index=models.Index(fields=['branch', 'op_type'], name='sync_operat_branch__df4c1b_idx'),
        ),
        migrations.AddIndex(
            model_name='syncoperation',
            index=models.Index(fields=['status'], name='sync_operat_status_4273a6_idx'),
        ),
        migrations.AddIndex(
            model_name='stockdiscrepancy',
            index=models.Index(fields=['branch', 'resolved'], name='stock_discr_branch__561eb6_idx'),
        ),
    ]
