# # Generated by Django 4.2.7 on 2025-10-02 20:53
# 
# import django.core.validators
# from django.db import migrations, models
# import django.db.models.deletion
# 
# 
# class Migration(migrations.Migration):
# 
#     initial = True
# 
#     dependencies = [
#         ('orders', '0001_initial'),
#     ]
# 
#     operations = [
#         migrations.CreateModel(
#             name='Payment',
#             fields=[
#                 ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                 ('method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('stripe', 'Stripe'), ('cash_on_delivery', 'Cash on Delivery')], default='mpesa', max_length=20, verbose_name='Payment Method')),
#                 ('status', models.CharField(choices=[('initiated', 'Initiated'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='initiated', max_length=20, verbose_name='Status')),
#                 ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Amount (KES)')),
#                 ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Transaction Reference')),
#                 ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Transaction ID')),
#                 ('transaction_date', models.DateTimeField(blank=True, null=True, verbose_name='Transaction Date')),
#                 ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
#                 ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
#                 ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
#                 ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='orders.order', verbose_name='Order')),
#             ],
#             options={
#                 'verbose_name': 'Payment',
#                 'verbose_name_plural': 'Payments',
#                 'db_table': 'payments',
#                 'ordering': ['-created_at'],
#                 'indexes': [models.Index(fields=['order', 'status'], name='payments_order_i_3d4604_idx'), models.Index(fields=['method'], name='payments_method_aea958_idx'), models.Index(fields=['created_at'], name='payments_created_e3a130_idx')],
#             },
#         ),
#     ]
