from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone
from django.db.models import Count, Sum, Avg
from prescriptions.models import Prescription
from products.models import Product
from patients.models import Patient
from django.core.serializers.json import DjangoJSONEncoder

User = get_user_model()


class Report(models.Model):
    """
    Model for storing generated reports.
    Supports various types: prescription volumes, inventory usage, turnaround times, patient trends.
    Data is stored as JSON for flexibility in visualizations.
    """

    REPORT_TYPES = [
        ("prescription_volume", "Prescription Volume"),
        ("inventory_usage", "Inventory Usage"),
        ("turnaround_times", "Turnaround Times"),
        ("patient_trends", "Patient Service Trends"),
        ("compliance_summary", "Compliance Summary"),
    ]

    type = models.CharField(
        max_length=50, choices=REPORT_TYPES, verbose_name="Report Type"
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="generated_reports",
        verbose_name="Generated By",
    )
    start_date = models.DateField(verbose_name="Start Date")
    end_date = models.DateField(verbose_name="End Date")
    data = models.JSONField(
        default=dict, encoder=DjangoJSONEncoder, verbose_name="Report Data"
    )
    total_count = models.PositiveIntegerField(default=0, verbose_name="Total Items")
    summary = models.TextField(blank=True, verbose_name="Summary")
    generated_at = models.DateTimeField(
        default=timezone.now, verbose_name="Generated At"
    )
    is_exported = models.BooleanField(default=False, verbose_name="Exported")

    class Meta:
        verbose_name = "Report"
        verbose_name_plural = "Reports"
        ordering = ["-generated_at"]
        indexes = [
            models.Index(fields=["type", "generated_at"]),
            models.Index(fields=["start_date", "end_date"]),
        ]

    def __str__(self):
        return (
            f"{self.get_type_display()} Report ({self.start_date} to {self.end_date})"
        )

    @classmethod
    def generate_prescription_volume(cls, user, start_date, end_date):
        """
        Generate prescription volume data.
        """
        prescriptions = (
            Prescription.objects.filter(uploaded_at__date__range=[start_date, end_date])
            .values("status")
            .annotate(count=Count("id"))
        )

        data = {
            "volumes": list(prescriptions),
            "total_prescriptions": sum(item["count"] for item in prescriptions),
            "daily_trend": list(
                Prescription.objects.filter(
                    uploaded_at__date__range=[start_date, end_date]
                )
                .extra({"date": "date(uploaded_at)"})
                .values("date")
                .annotate(count=Count("id"))
                .order_by("date")
            ),
        }

        report = cls(
            type="prescription_volume",
            user=user,
            start_date=start_date,
            end_date=end_date,
            data=data,
            total_count=data["total_prescriptions"],
            summary=f"Total prescriptions: {data['total_prescriptions']}",
        )
        report.save()
        return report

    @classmethod
    def generate_inventory_usage(cls, user, start_date, end_date):
        """
        Generate inventory usage data (based on product stock changes or orders).
        Note: Assumes usage tracked via orders or stock logs; extend as needed.
        """
        # Example: Aggregate product stock levels or usage
        products = (
            Product.objects.filter(created_at__date__range=[start_date, end_date])
            .values("category")
            .annotate(total_stock=Sum("stock_quantity"), avg_price=Avg("price"))
        )

        data = {
            "usage_by_category": list(products),
            "low_stock_items": list(
                Product.objects.filter(stock_quantity__lt=10).values(
                    "name", "stock_quantity", "pharmacy__name"
                )[:10]
            ),
        }

        report = cls(
            type="inventory_usage",
            user=user,
            start_date=start_date,
            end_date=end_date,
            data=data,
            total_count=Product.objects.count(),
            summary=f"Categories with low stock: {len(data['low_stock_items'])}",
        )
        report.save()
        return report

    @classmethod
    def generate_turnaround_times(cls, user, start_date, end_date):
        """
        Generate turnaround times for prescriptions.
        Assumes verified_at - uploaded_at for calculation.
        """
        prescriptions = Prescription.objects.filter(
            uploaded_at__date__range=[start_date, end_date], status="verified"
        ).annotate(turnaround_hours=models.F("verified_at") - models.F("uploaded_at"))

        avg_turnaround = prescriptions.aggregate(avg=models.Avg("turnaround_hours"))[
            "avg"
        ]

        data = {
            "average_turnaround_hours": avg_turnaround,
            "distribution": list(
                prescriptions.values("status").annotate(count=Count("id"))
            ),
            "max_turnaround": prescriptions.aggregate(
                max=models.Max("turnaround_hours")
            )["max"],
        }

        report = cls(
            type="turnaround_times",
            user=user,
            start_date=start_date,
            end_date=end_date,
            data=data,
            total_count=prescriptions.count(),
            summary=f"Average turnaround: {avg_turnaround:.2f} hours",
        )
        report.save()
        return report

    @classmethod
    def generate_patient_trends(cls, user, start_date, end_date):
        """
        Generate patient service trends.
        """
        patients = (
            Patient.objects.filter(created_at__date__range=[start_date, end_date])
            .values("county")
            .annotate(count=Count("id"))
        )

        data = {
            "new_patients_by_county": list(patients),
            "total_new_patients": sum(item["count"] for item in patients),
            "demographics": list(
                Patient.objects.filter(created_at__date__range=[start_date, end_date])
                .values("gender")
                .annotate(count=Count("id"))
            ),
        }

        report = cls(
            type="patient_trends",
            user=user,
            start_date=start_date,
            end_date=end_date,
            data=data,
            total_count=data["total_new_patients"],
            summary=f"New patients: {data['total_new_patients']}",
        )
        report.save()
        return report
