# # Generated by Django 4.2.7 on 2025-10-03 14:25
# 
# from django.conf import settings
# from django.db import migrations, models
# import django.db.models.deletion
# 
# 
# class Migration(migrations.Migration):
# 
#     dependencies = [
#         migrations.swappable_dependency(settings.AUTH_USER_MODEL),
#         ('products', '0001_initial'),
#     ]
# 
#     operations = [
#         migrations.CreateModel(
#             name='StockLog',
#             fields=[
#                 ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                 ('previous_quantity', models.PositiveIntegerField(verbose_name='Previous Quantity')),
#                 ('new_quantity', models.PositiveIntegerField(verbose_name='New Quantity')),
#                 ('change_amount', models.IntegerField(verbose_name='Change Amount')),
#                 ('change_type', models.CharField(choices=[('restock', 'Restock'), ('sale', 'Sale'), ('adjustment', 'Adjustment'), ('expiry', 'Expiry')], max_length=20, verbose_name='Change Type')),
#                 ('reason', models.CharField(blank=True, max_length=255, verbose_name='Reason')),
#                 ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
#                 ('alert_triggered', models.BooleanField(default=False, verbose_name='Low-Stock Alert Triggered')),
#             ],
#             options={
#                 'verbose_name': 'Stock Log',
#                 'verbose_name_plural': 'Stock Logs',
#                 'db_table': 'stock_logs',
#                 'ordering': ['-timestamp'],
#             },
#         ),
#         migrations.AddField(
#             model_name='product',
#             name='reorder_threshold',
#             field=models.PositiveIntegerField(default=10, verbose_name='Reorder Threshold'),
#         ),
#         migrations.AddIndex(
#             model_name='product',
#             index=models.Index(fields=['is_active'], name='products_is_acti_cb485f_idx'),
#         ),
#         migrations.AddField(
#             model_name='stocklog',
#             name='logged_by',
#             field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_logs', to=settings.AUTH_USER_MODEL, verbose_name='Logged By'),
#         ),
#         migrations.AddField(
#             model_name='stocklog',
#             name='product',
#             field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_logs', to='products.product', verbose_name='Product'),
#         ),
#         migrations.AddIndex(
#             model_name='stocklog',
#             index=models.Index(fields=['product', 'timestamp'], name='stock_logs_product_ac5cab_idx'),
#         ),
#         migrations.AddIndex(
#             model_name='stocklog',
#             index=models.Index(fields=['change_type'], name='stock_logs_change__8b91b6_idx'),
#         ),
#         migrations.AddIndex(
#             model_name='stocklog',
#             index=models.Index(fields=['alert_triggered'], name='stock_logs_alert_t_5a43ee_idx'),
#         ),
#     ]
