# Generated by Django 4.2.7 on 2025-12-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('pharmacist', 'Pharmacist'), ('admin', 'Admin'), ('cashier', 'Cashier'), ('auditor', 'Auditor')], default='customer', max_length=20),
        ),
    ]
