# Generated by Django 4.2.7 on 2025-12-12 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Pharmacy Name')),
                ('address', models.TextField(verbose_name='Address')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Contact Phone')),
                ('license_number', models.CharField(max_length=50, unique=True, verbose_name='License Number')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pharmacy',
                'verbose_name_plural': 'Pharmacies',
                'db_table': 'pharmacies',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='pharmacy',
            field=models.ForeignKey(blank=True, help_text='The pharmacy this user belongs to (for pharmacists/staff).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.pharmacy', verbose_name='Pharmacy'),
        ),
    ]
