# Generated by Django 4.2.7 on 2025-12-12 10:47

from django.db import migrations


def create_default_pharmacy(apps, schema_editor):
    Pharmacy = apps.get_model('users', 'Pharmacy')
    User = apps.get_model('users', 'User')
    Product = apps.get_model('products', 'Product')

    # Create default pharmacy
    pharmacy, created = Pharmacy.objects.get_or_create(
        name="Main Pharmacy",
        defaults={
            "address": "123 Main St, Nairobi",
            "contact_phone": "+254700000000",
            "license_number": "PHARM-001"
        }
    )

    # Assign to all users
    User.objects.update(pharmacy=pharmacy)

    # Assign to all products
    Product.objects.update(pharmacy=pharmacy)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_pharmacy_user_pharmacy'),
        ('products', '0008_product_pharmacy'),
    ]

    operations = [
        migrations.RunPython(create_default_pharmacy, reverse_code=migrations.RunPython.noop),
    ]
