# Generated by Django 4.2.7 on 2025-12-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_create_default_pharmacy'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_role_0ace22_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['pharmacy'], name='users_pharmac_f2117f_idx'),
        ),
    ]
