# Generated by Django 4.2.7 on 2026-02-18 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_users_role_0ace22_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('license', 'Pharmacy License'), ('permit', 'Operational Permit'), ('insurance', 'Insurance Certificate'), ('compliance', 'Compliance Certificate'), ('other', 'Other Document')], default='other', max_length=20, verbose_name='Document Type')),
                ('title', models.CharField(max_length=255, verbose_name='Document Title')),
                ('file', models.FileField(upload_to='pharmacy_documents/', verbose_name='Document File')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is Verified')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='users.pharmacy', verbose_name='Pharmacy')),
            ],
            options={
                'verbose_name': 'Pharmacy Document',
                'verbose_name_plural': 'Pharmacy Documents',
                'db_table': 'pharmacy_documents',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['pharmacy', 'document_type'], name='pharmacy_do_pharmac_b67e12_idx'), models.Index(fields=['expiry_date'], name='pharmacy_do_expiry__b68531_idx')],
            },
        ),
    ]
