# Generated by Django 4.2.7 on 2026-02-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_pharmacydocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Designates whether the user must change their password upon login.'),
        ),
    ]
