# Generated by Django 4.2.7 on 2026-05-22 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_must_change_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Branch Name')),
                ('address', models.TextField(verbose_name='Address')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Contact Phone')),
                ('license_number', models.CharField(blank=True, max_length=50, verbose_name='Branch Licence Number')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_headquarters', models.BooleanField(default=False, help_text='Mark if this is the main/head office branch.', verbose_name='Is Headquarters')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='users.pharmacy', verbose_name='Pharmacy')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
                'db_table': 'branches',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='The branch this staff member is primarily assigned to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.branch', verbose_name='Branch'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['pharmacy'], name='branches_pharmac_bda7ba_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['is_active'], name='branches_is_acti_830392_idx'),
        ),
    ]
