# Generated by Django 4.2.7 on 2026-05-29 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_seed_default_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credit_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Outstanding debt or credit balance for customers', max_digits=15, verbose_name='Credit Balance'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_credit_customer',
            field=models.BooleanField(default=False, verbose_name='Is Credit Customer'),
        ),
        migrations.CreateModel(
            name='CustomerDebtTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('SALE_ON_CREDIT', 'Sale on Credit'), ('PAYMENT', 'Payment Received'), ('ADJUSTMENT', 'Balance Adjustment')], max_length=20, verbose_name='Transaction Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Balance After')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('legacy_tid', models.CharField(blank=True, max_length=100, null=True, verbose_name='Legacy Transaction ID')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_debt_transactions', to='users.branch', verbose_name='Branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customer_debt_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Customer Debt Transaction',
                'verbose_name_plural': 'Customer Debt Transactions',
                'db_table': 'customer_debt_transactions',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['customer', 'timestamp'], name='customer_de_custome_525472_idx'), models.Index(fields=['legacy_tid'], name='customer_de_legacy__fb51e3_idx')],
            },
        ),
    ]
