# Generated by Django 4.2.7 on 2026-05-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_credit_balance_user_is_credit_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_delete_records',
            field=models.BooleanField(default=False, verbose_name='Can Delete Records'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_edit_prices',
            field=models.BooleanField(default=False, verbose_name='Can Edit Prices'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_inventory',
            field=models.BooleanField(default=False, verbose_name='Can Manage Inventory'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_users',
            field=models.BooleanField(default=False, verbose_name='Can Manage Users'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_process_sales',
            field=models.BooleanField(default=False, verbose_name='Can Process Sales'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_audit_logs',
            field=models.BooleanField(default=False, verbose_name='Can View Audit Logs'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_reports',
            field=models.BooleanField(default=False, verbose_name='Can View Reports'),
        ),
    ]
