# Generated by Django

from django.db import migrations

def populate_permissions(apps, schema_editor):
    User = apps.get_model('users', 'User')
    
    for user in User.objects.all():
        if user.is_superuser or user.role == 'admin':
            user.can_process_sales = True
            user.can_manage_inventory = True
            user.can_edit_prices = True
            user.can_view_reports = True
            user.can_manage_users = True
            user.can_delete_records = True
            user.can_view_audit_logs = True
        elif user.role == 'pharmacist':
            user.can_process_sales = True
            user.can_manage_inventory = True
        elif user.role == 'cashier':
            user.can_process_sales = True
        elif user.role == 'auditor':
            user.can_view_reports = True
            user.can_view_audit_logs = True
            
        user.save()

def reverse_permissions(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User.objects.update(
        can_process_sales=False,
        can_manage_inventory=False,
        can_edit_prices=False,
        can_view_reports=False,
        can_manage_users=False,
        can_delete_records=False,
        can_view_audit_logs=False,
    )

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_can_delete_records_user_can_edit_prices_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_permissions, reverse_permissions),
    ]
