# Generated by Django 4.2.7 on 2026-05-29 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_populate_user_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('sale', 'Sale Processed'), ('edit_price', 'Price Edited'), ('restock', 'Stock Intake'), ('delete_record', 'Record Deleted'), ('other', 'Other Action')], default='other', max_length=20)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Activity Log',
                'verbose_name_plural': 'Staff Activity Logs',
                'db_table': 'staff_activity_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='staff_activ_user_id_f4153c_idx'), models.Index(fields=['action_type'], name='staff_activ_action__6c2ef3_idx')],
            },
        ),
    ]
