# Generated by Django 4.2.7

import os
import re
from datetime import datetime, time
from django.db import migrations
from django.utils import timezone

def parse_inserts(filepath, table_name):
    rows = []
    pattern = re.compile(
        rf"INSERT\s+INTO\s+`?{re.escape(table_name)}`?\s+VALUES\s*",
        re.IGNORECASE,
    )
    if not os.path.exists(filepath):
        return rows

    with open(filepath, "r", encoding="latin1") as f:
        for line in f:
            if not pattern.match(line):
                continue
            _, _, values_part = line.partition("VALUES")
            values_part = values_part.strip().rstrip(";").strip()
            rows.extend(_split_value_tuples(values_part))
    return rows

def _split_value_tuples(values_str):
    tuples = []
    depth = 0
    current = []
    i = 0
    while i < len(values_str):
        ch = values_str[i]
        if ch == "(" and depth == 0:
            depth = 1
            current = []
        elif ch == "(" and depth > 0:
            depth += 1
            current.append(ch)
        elif ch == ")" and depth == 1:
            depth = 0
            tuples.append("".join(current))
        elif ch == ")" and depth > 1:
            depth -= 1
            current.append(ch)
        elif ch == "'" and depth > 0:
            j = i + 1
            parts = ["'"]
            while j < len(values_str):
                c = values_str[j]
                parts.append(c)
                if c == "\\" and j + 1 < len(values_str):
                    parts.append(values_str[j + 1])
                    j += 2
                    continue
                if c == "'":
                    if j + 1 < len(values_str) and values_str[j + 1] == "'":
                        parts.append("'")
                        j += 2
                        continue
                    break
                j += 1
            current.append("".join(parts))
            i = j
        elif depth > 0:
            current.append(ch)
        i += 1
    return tuples

def parse_tuple_values(tuple_str):
    values = []
    i = 0
    s = tuple_str
    while i < len(s):
        ch = s[i]
        if ch in (" ", "\t"):
            i += 1
            continue
        if ch == ",":
            i += 1
            continue
        if ch == "'":
            j = i + 1
            parts = []
            while j < len(s):
                c = s[j]
                if c == "\\":
                    if j + 1 < len(s):
                        nc = s[j + 1]
                        if nc == "'": parts.append("'")
                        elif nc == "\\": parts.append("\\")
                        elif nc == "n": parts.append("\n")
                        elif nc == "r": parts.append("\r")
                        elif nc == "t": parts.append("\t")
                        else: parts.append(nc)
                        j += 2
                        continue
                if c == "'":
                    if j + 1 < len(s) and s[j + 1] == "'":
                        parts.append("'")
                        j += 2
                        continue
                    break
                parts.append(c)
                j += 1
            values.append("".join(parts))
            i = j + 1
        elif s[i : i + 4].upper() == "NULL":
            values.append(None)
            i += 4
        else:
            j = i
            while j < len(s) and s[j] not in (",", ")"):
                j += 1
            token = s[i:j].strip()
            try:
                if "." in token: values.append(float(token))
                else: values.append(int(token))
            except ValueError:
                values.append(token)
            i = j
    return values

def import_activehours(apps, schema_editor):
    User = apps.get_model('users', 'User')
    StaffActivityLog = apps.get_model('users', 'StaffActivityLog')
    
    sql_file = "/home/steve/pharmacy-aggregator/database/transcount.sql"
    rows = parse_inserts(sql_file, "activehours")
    
    logs = []
    
    users_cache = {}
    
    for row_str in rows:
        vals = parse_tuple_values(row_str)
        if len(vals) < 6:
            continue
            
        logtime, lastseen, username, day, month, year = vals[:6]
        
        if username not in users_cache:
            user = User.objects.filter(username__iexact=username).first()
            users_cache[username] = user
            
        user = users_cache[username]
        if not user:
            continue
            
        try:
            # Parse Date
            date_str = f"{year} {month} {day}"
            date_obj = datetime.strptime(date_str, "%Y %B %d").date()
            
            # Parse Logtime (Login)
            if logtime:
                time_in = datetime.strptime(str(logtime), "%H:%M:%S").time()
                login_dt = timezone.make_aware(datetime.combine(date_obj, time_in))
                
                logs.append(StaffActivityLog(
                    user=user,
                    action_type='login',
                    description='Legacy Login Record',
                    timestamp=login_dt
                ))
            
            # Parse Lastseen (Logout)
            if lastseen:
                time_out = datetime.strptime(str(lastseen), "%H:%M:%S").time()
                logout_dt = timezone.make_aware(datetime.combine(date_obj, time_out))
                
                logs.append(StaffActivityLog(
                    user=user,
                    action_type='logout',
                    description='Legacy Logout Record',
                    timestamp=logout_dt
                ))
                
        except ValueError:
            continue
            
    if logs:
        # bulk_create ignores auto_now_add if we specify timestamp explicitly in some versions,
        # but in Django 4.2 we might need to be careful. Since timestamp is auto_now_add,
        # bulk_create might override it. Let's save them individually or use bulk_create
        for log in logs:
            log.save()

def reverse_import(apps, schema_editor):
    StaffActivityLog = apps.get_model('users', 'StaffActivityLog')
    StaffActivityLog.objects.filter(description__startswith='Legacy').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_staffactivitylog'),
    ]

    operations = [
        migrations.RunPython(import_activehours, reverse_import),
    ]
