# Generated by Django 4.2.7 on 2026-05-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_import_activehours'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_view_financials',
            field=models.BooleanField(default=False, verbose_name='Can View Financials'),
        ),
    ]
