# Generated by Django 4.2.7 on 2026-05-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_can_view_financials_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='staffactivitylog',
            index=models.Index(fields=['user', 'timestamp'], name='staff_activ_user_id_f4153c_idx'),
        ),
    ]
