# Generated by Django 4.2.7 on 2026-05-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_staffactivitylog_staff_activ_user_id_f4153c_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permission_flags',
            field=models.JSONField(blank=True, default=dict, help_text='Granular permission flags for the frontend and admin dashboard.', verbose_name='Permission Flags'),
        ),
    ]
