# Generated by Django 4.2.7 on 2026-06-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_customerdebttransaction_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffactivitylog',
            name='details',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
