# Generated by Django 4.2.7 on 2026-06-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_staffactivitylog_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='tagline',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tagline'),
        ),
    ]
