# Generated by Django 4.2.7 on 2026-06-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_user_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_transfer_stock',
            field=models.BooleanField(default=False, help_text='Can view other-branch stock quantities and request transfers.', verbose_name='Can Transfer Stock'),
        ),
    ]
